// @generated
// This file is @generated by prost-build.
/// Request is the input message for the `Stream.Blocks` RPC. It specifies which blocks to
/// stream, which Substreams modules to execute, and various options that control the
/// execution mode and output.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    /// If positive, the absolute block number at which to start streaming (inclusive).
    /// If 0, streaming starts at the first streamable block of the chain.
    /// If negative, the start block is resolved relative to the chain HEAD at the time of
    /// the request (e.g., -10 starts 10 blocks before the current HEAD).
    #[prost(int64, tag="1")]
    pub start_block_num: i64,
    /// Cursor returned by a previous `BlockScopedData.cursor` or
    /// `BlockUndoSignal.last_valid_cursor`. When provided, streaming resumes from the exact
    /// position the cursor points to, taking precedence over `start_block_num`. Use this to
    /// implement reliable exactly-once resumption after disconnections or forks.
    #[prost(string, tag="2")]
    pub start_cursor: ::prost::alloc::string::String,
    /// If non-zero, streaming stops *before* reaching this block number (exclusive upper bound).
    /// If zero, the stream continues indefinitely, following the chain HEAD in real-time.
    #[prost(uint64, tag="3")]
    pub stop_block_num: u64,
    /// With final_block_only, you only receive blocks that are irreversible:
    /// 'final_block_height' will be equal to current block and no 'undo_signal' will ever be sent
    #[prost(bool, tag="4")]
    pub final_blocks_only: bool,
    /// Substreams has two mode when executing your module(s) either development mode or production
    /// mode. Development and production modes impact the execution of Substreams, important aspects
    /// of execution include:
    /// * The time required to reach the first byte.
    /// * The speed that large ranges get executed.
    /// * The module logs and outputs sent back to the client.
    ///
    /// By default, the engine runs in developer mode, with richer and deeper output. Differences
    /// between production and development modes include:
    /// * Forward parallel execution is enabled in production mode and disabled in development mode
    /// * The time required to reach the first byte in development mode is faster than in production mode.
    ///
    /// Specific attributes of development mode include:
    /// * The client will receive all of the executed module's logs.
    /// * It's possible to request specific store snapshots in the execution tree (via `debug_initial_store_snapshot_for_modules`).
    /// * Multiple module's output is possible.
    ///
    /// With production mode`, however, you trade off functionality for high speed enabling forward
    /// parallel execution of module ahead of time.
    #[prost(bool, tag="5")]
    pub production_mode: bool,
    /// Name of the module whose output should be streamed back to the client. Must be a
    /// `map` module. Only one output module is supported per request.
    #[prost(string, tag="6")]
    pub output_module: ::prost::alloc::string::String,
    /// Substreams module definitions to execute. At minimum this must contain the module
    /// named by `output_module` and all of its transitive dependencies.
    #[prost(message, optional, tag="7")]
    pub modules: ::core::option::Option<super::super::v1::Modules>,
    /// Available only in developer mode
    #[prost(string, repeated, tag="10")]
    pub debug_initial_store_snapshot_for_modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// When true, prepares the stores and caches on the server without sending any module
    /// output. Only progress messages and minimal clock/cursor data are returned. Useful for
    /// pre-warming caches (e.g., to reduce latency for a subsequent real request) without
    /// incurring the cost of transmitting full block data.
    #[prost(bool, tag="11")]
    pub noop_mode: bool,
    /// If set, the engine will reject a request if the number of blocks to process (including preparing the stores) is above this limit.
    /// Useful as a safeguard for managing costs
    #[prost(uint64, tag="12")]
    pub limit_processed_blocks: u64,
    /// Available only in developer mode
    /// If set, the server will only send the output of these modules.
    /// If unset, all the outputs are sent.
    /// This allows the user to reduce the payload in dev mode, while still getting some extra debugging information
    #[prost(string, repeated, tag="13")]
    pub dev_output_modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Progress_messages_interval_ms is the interval between progress messages, in milliseconds (minimum: 500, default: start at 500ms and ramp up to 5000ms within 1min)
    #[prost(uint64, tag="14")]
    pub progress_messages_interval_ms: u64,
    /// If true, blocks close to head will be sent in "partials" as soon as we get them.
    /// This means that you will get different versions of the same block number, each an incomplete increment
    /// Other blocks will be sent completely (older blocks, or blocks for which the provider did not get a partial in time)
    #[prost(bool, tag="16")]
    pub partial_blocks: bool,
}
/// Response is the output message streamed back by the `Stream.Blocks` RPC.
/// Each response contains exactly one of the possible message types.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(oneof="response::Message", tags="1, 2, 3, 4, 5, 10, 11")]
    pub message: ::core::option::Option<response::Message>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// Always sent first when the stream opens.
        #[prost(message, tag="1")]
        Session(super::SessionInit),
        /// Progress of data preparation, before sending in the stream of `data` events.
        #[prost(message, tag="2")]
        Progress(super::ModulesProgress),
        #[prost(message, tag="3")]
        BlockScopedData(super::BlockScopedData),
        #[prost(message, tag="4")]
        BlockUndoSignal(super::BlockUndoSignal),
        #[prost(message, tag="5")]
        FatalError(super::Error),
        /// Available only in developer mode, and only if `debug_initial_store_snapshot_for_modules` is set.
        #[prost(message, tag="10")]
        DebugSnapshotData(super::InitialSnapshotData),
        /// Available only in developer mode, and only if `debug_initial_store_snapshot_for_modules` is set.
        #[prost(message, tag="11")]
        DebugSnapshotComplete(super::InitialSnapshotComplete),
    }
}
/// BlockUndoSignal is sent when a chain reorganization (fork) has occurred, indicating that
/// some previously streamed block data is no longer part of the canonical chain and must be
/// invalidated. Upon receiving this signal, delete all stored data for blocks whose number
/// is strictly greater than `last_valid_block.number`, then resume the stream using
/// `last_valid_cursor`.
///
/// A single BlockUndoSignal may revert multiple consecutive blocks. For example, suppose
/// your sink has processed blocks 100, 101, 102, and 103. If the chain reorganizes and the
/// new canonical chain diverges starting after block 98, you will receive a single
/// BlockUndoSignal with `last_valid_block.number = 98`. You must then delete all reversible
/// data you stored for blocks 99, 100, 101, 102, and 103.
///
/// "Reversible" data refers to data stored for blocks whose number is greater than the
/// most recently received `BlockScopedData.final_block_height`. Once a block's number is
/// at or below `final_block_height`, that data is considered final (irreversible) and will
/// never be the subject of a future undo signal.
///
/// Best practice: atomically delete reversible data AND persist `last_valid_cursor`
/// together in the same transaction. This guarantees that on reconnection (using the
/// persisted cursor), the stream resumes exactly at the last valid block, even if a
/// disconnection occurred in the middle of a fork resolution.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockUndoSignal {
    /// The highest block that is still valid in the canonical chain after the reorganization.
    /// Delete all stored data for blocks with a number strictly greater than this block's number.
    #[prost(message, optional, tag="1")]
    pub last_valid_block: ::core::option::Option<super::super::v1::BlockRef>,
    /// The cursor corresponding to `last_valid_block`. Persist this cursor atomically with
    /// your data deletions so that on reconnection the stream resumes from exactly this point.
    #[prost(string, tag="2")]
    pub last_valid_cursor: ::prost::alloc::string::String,
}
/// BlockScopedData contains the processed output for a single block and is the primary
/// data-bearing message in the stream.
///
/// Cursor handling and resumption:
/// Persist `cursor` atomically together with your processed data (ideally in the same
/// transaction) after every block. On reconnection, pass the persisted cursor as
/// `Request.start_cursor` to resume the stream from exactly where you left off, with no
/// duplicates and no gaps — even if a disconnection happened mid-fork.
///
/// If your storage backend does not support transactions, a practical alternative is:
/// on startup, delete all stored data for blocks whose number is >= the last persisted
/// block number before resuming. This removes any half-written data from a previous
/// interrupted run and ensures a clean state before the stream continues.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockScopedData {
    /// The output produced by the `output_module` for this block. The `map_output` field
    /// within contains the module's Protobuf-encoded result.
    #[prost(message, optional, tag="1")]
    pub output: ::core::option::Option<MapModuleOutput>,
    /// Clock information for this block: its hash (`id`), height (`number`), and timestamp.
    #[prost(message, optional, tag="2")]
    pub clock: ::core::option::Option<super::super::v1::Clock>,
    /// Opaque cursor identifying the exact stream position at this block. Persist this
    /// value and pass it as `Request.start_cursor` to resume the stream after a
    /// disconnection. This cursor is safe to persist even when `final_block_height` has
    /// not yet reached this block's number.
    #[prost(string, tag="3")]
    pub cursor: ::prost::alloc::string::String,
    /// The block number of the highest block that has reached finality (irreversibility) at
    /// the time this message was produced. Data for blocks at or below this number will
    /// never be undone and can be treated as permanent. Non-deterministic: may advance
    /// in larger steps as the chain progresses.
    #[prost(uint64, tag="4")]
    pub final_block_height: u64,
    #[prost(message, repeated, tag="10")]
    pub debug_map_outputs: ::prost::alloc::vec::Vec<MapModuleOutput>,
    #[prost(message, repeated, tag="11")]
    pub debug_store_outputs: ::prost::alloc::vec::Vec<StoreModuleOutput>,
    /// Signed attestation, enabling economic security as per GIP-0083. Signatures are
    /// done using the key specified by SessionInit::attestation_public_key.
    #[prost(string, tag="12")]
    pub attestation: ::prost::alloc::string::String,
    /// true if this is a partial block, meaning that it contains only parts of the block data and that its hash will be replaced
    #[prost(bool, tag="13")]
    pub is_partial: bool,
    /// Only present if is_partial==true
    #[prost(uint32, optional, tag="14")]
    pub partial_index: ::core::option::Option<u32>,
    /// Only present if is_partial==true
    /// True if this is the last partial payload for this block number. The `clock.id` (block
    /// hash) carried in this message is the final, definitive hash for the block. Prior
    /// partials for the same block number will have had a tentative or empty hash.
    ///
    /// Partial block support is currently implemented for Flashblocks, the pre-confirmation
    /// block stream used on Base and Optimism. A single canonical block is typically split
    /// into multiple incremental partials; the last one carries the block's true hash.
    #[prost(bool, optional, tag="15")]
    pub is_last_partial: ::core::option::Option<bool>,
}
/// SessionInit is the first message sent in the stream. It provides metadata about the
/// server-side execution session such as the resolved start block and parallelism settings.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionInit {
    /// Unique trace identifier for this stream session. Useful for correlating logs and
    /// debugging issues with the provider.
    #[prost(string, tag="1")]
    pub trace_id: ::prost::alloc::string::String,
    /// The actual block number at which streaming will start, after resolving a relative
    /// `start_block_num` or a cursor. Use this to verify that the stream begins where expected.
    #[prost(uint64, tag="2")]
    pub resolved_start_block: u64,
    /// The block number at which the server transitions from parallel (historical) processing
    /// to linear (real-time) processing. Blocks before this number are produced by
    /// parallel workers; blocks at and after this number are produced sequentially.
    #[prost(uint64, tag="3")]
    pub linear_handoff_block: u64,
    /// The maximum number of parallel workers the server may use to process historical blocks
    /// for this request.
    #[prost(uint64, tag="4")]
    pub max_parallel_workers: u64,
    /// Operator's attestation public_key or address, enabling economic security as per GIP-0083.
    #[prost(string, tag="5")]
    pub attestation_public_key: ::prost::alloc::string::String,
    /// The current HEAD block number of the chain at the time the session was initialized.
    #[prost(uint64, tag="6")]
    pub chain_head: u64,
    /// theoretical number of blocks that need to be processed __before any data is sent__, without consideration for current cached states
    /// Because of parallel work, 1000 blocks with 2 "store stages" will result in 2000 blocks to process
    #[prost(uint64, tag="7")]
    pub blocks_to_process_before_start_block: u64,
    /// same as `blocks_to_process_before_start_block`, but excluding the current cached states
    #[prost(uint64, tag="8")]
    pub effective_blocks_to_process_before_start_block: u64,
    /// theoretical number of blocks that will be processed inside the requested range, without consideration for current cached outputs
    /// if the range is open-ended, it is calculated up to the current chain head
    /// in production-mode, 1000 blocks with 3 "stages" will result in 3000 blocks to process
    #[prost(uint64, tag="9")]
    pub blocks_to_process_after_start_block: u64,
    /// same as `blocks_to_process_after_start_block`, but excluding the current cached outputs
    #[prost(uint64, tag="10")]
    pub effective_blocks_to_process_after_start_block: u64,
}
/// InitialSnapshotComplete is sent in developer mode after all InitialSnapshotData
/// messages for a module have been delivered, signaling that the full initial store
/// snapshot has been transmitted.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialSnapshotComplete {
    /// The cursor at the point the snapshot was taken. Use this as `start_cursor` if you
    /// want to resume the stream from exactly after the snapshot.
    #[prost(string, tag="1")]
    pub cursor: ::prost::alloc::string::String,
}
/// InitialSnapshotData carries a batch of key-value deltas from a store module's initial
/// state snapshot. Only available in developer mode when
/// `debug_initial_store_snapshot_for_modules` is set.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialSnapshotData {
    /// Name of the store module whose initial snapshot is being sent.
    #[prost(string, tag="1")]
    pub module_name: ::prost::alloc::string::String,
    /// A batch of store deltas representing part of the module's full key-value state.
    #[prost(message, repeated, tag="2")]
    pub deltas: ::prost::alloc::vec::Vec<StoreDelta>,
    /// The number of keys sent so far across all batches for this module.
    #[prost(uint64, tag="4")]
    pub sent_keys: u64,
    /// The total number of keys in the store module's full initial snapshot.
    #[prost(uint64, tag="3")]
    pub total_keys: u64,
}
/// MapModuleOutput holds the Protobuf-encoded output of a single `map` module for a block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapModuleOutput {
    /// The name of the map module that produced this output.
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// The Protobuf-encoded output value. The concrete message type is determined by the
    /// module's `output.type` declaration in the Substreams manifest.
    #[prost(message, optional, tag="2")]
    pub map_output: ::core::option::Option<::prost_types::Any>,
    /// DebugOutputInfo is available in non-production mode only
    #[prost(message, optional, tag="10")]
    pub debug_info: ::core::option::Option<OutputDebugInfo>,
}
/// StoreModuleOutput are produced for store modules in development mode.
/// It is not possible to retrieve store models in production, with parallelization
/// enabled. If you need the deltas directly, write a pass through mapper module
/// that will get them down to you.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreModuleOutput {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub debug_store_deltas: ::prost::alloc::vec::Vec<StoreDelta>,
    #[prost(message, optional, tag="10")]
    pub debug_info: ::core::option::Option<OutputDebugInfo>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OutputDebugInfo {
    #[prost(string, repeated, tag="1")]
    pub logs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// LogsTruncated is a flag that tells you if you received all the logs or if they
    /// were truncated because you logged too much (fixed limit currently is set to 128 KiB).
    #[prost(bool, tag="2")]
    pub logs_truncated: bool,
    #[prost(bool, tag="3")]
    pub cached: bool,
}
/// ModulesProgress is a message that is sent every 500ms
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModulesProgress {
    /// List of jobs running on tier2 servers
    #[prost(message, repeated, tag="2")]
    pub running_jobs: ::prost::alloc::vec::Vec<Job>,
    /// Execution statistics for each module
    #[prost(message, repeated, tag="3")]
    pub modules_stats: ::prost::alloc::vec::Vec<ModuleStats>,
    /// Stages definition and completed block ranges
    #[prost(message, repeated, tag="4")]
    pub stages: ::prost::alloc::vec::Vec<Stage>,
    #[prost(message, optional, tag="5")]
    pub processed_bytes: ::core::option::Option<ProcessedBytes>,
    #[prost(uint64, tag="6")]
    pub processed_blocks: u64,
}
/// ProcessedBytes reports the total volume of data read and written during parallel
/// processing. These are cumulative counters reset per session.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ProcessedBytes {
    /// Total number of bytes read from the block store during processing.
    #[prost(uint64, tag="1")]
    pub total_bytes_read: u64,
    /// Total number of bytes written to intermediate stores during processing.
    #[prost(uint64, tag="2")]
    pub total_bytes_written: u64,
}
/// Error represents a fatal module execution error. When received, the stream will be
/// terminated by the server immediately after this message.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Error {
    /// The name of the module that caused the fatal error.
    #[prost(string, tag="1")]
    pub module: ::prost::alloc::string::String,
    /// A human-readable description of why the module failed.
    #[prost(string, tag="2")]
    pub reason: ::prost::alloc::string::String,
    /// Log lines emitted by the failing module up to the point of failure.
    #[prost(string, repeated, tag="3")]
    pub logs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// FailureLogsTruncated is a flag that tells you if you received all the logs or if they
    /// were truncated because you logged too much (fixed limit currently is set to 128 KiB).
    #[prost(bool, tag="4")]
    pub logs_truncated: bool,
}
/// Job represents a single parallel processing unit running on a tier2 worker. Jobs process
/// a contiguous block range for a specific execution stage.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Job {
    /// The index of the execution stage this job belongs to (0-based).
    #[prost(uint32, tag="1")]
    pub stage: u32,
    /// The first block number in the range processed by this job (inclusive).
    #[prost(uint64, tag="2")]
    pub start_block: u64,
    /// The last block number in the range processed by this job (exclusive).
    #[prost(uint64, tag="3")]
    pub stop_block: u64,
    /// The number of blocks processed so far by this job within its range.
    #[prost(uint64, tag="4")]
    pub progress_blocks: u64,
    /// The wall-clock time in milliseconds this job has been running.
    #[prost(uint64, tag="5")]
    pub duration_ms: u64,
}
/// Stage represents one layer of the module execution DAG. Modules are grouped into stages
/// based on their dependencies; all modules in a stage can be executed independently of
/// each other but depend on modules in earlier stages.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stage {
    /// The names of the modules that belong to this execution stage.
    #[prost(string, repeated, tag="1")]
    pub modules: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// The block ranges that have been fully processed and cached for this stage.
    #[prost(message, repeated, tag="2")]
    pub completed_ranges: ::prost::alloc::vec::Vec<BlockRange>,
}
/// ModuleStats gathers metrics and statistics from each module, running on tier1 or tier2
/// All the 'count' and 'time_ms' values may include duplicate for each stage going over that module
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleStats {
    /// name of the module
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// total_processed_blocks is the sum of blocks sent to that module code
    #[prost(uint64, tag="2")]
    pub total_processed_block_count: u64,
    /// total_processing_time_ms is the sum of all time spent running that module code
    #[prost(uint64, tag="3")]
    pub total_processing_time_ms: u64,
    /// // external_calls are chain-specific intrinsics, like "Ethereum RPC calls".
    #[prost(message, repeated, tag="4")]
    pub external_call_metrics: ::prost::alloc::vec::Vec<ExternalCallMetric>,
    /// total_store_operation_time_ms is the sum of all time spent running that module code waiting for a store operation (ex: read, write, delete...)
    #[prost(uint64, tag="5")]
    pub total_store_operation_time_ms: u64,
    /// total_store_read_count is the sum of all the store Read operations called from that module code
    #[prost(uint64, tag="6")]
    pub total_store_read_count: u64,
    /// total_store_write_count is the sum of all store Write operations called from that module code (store-only)
    #[prost(uint64, tag="10")]
    pub total_store_write_count: u64,
    /// total_store_deleteprefix_count is the sum of all store DeletePrefix operations called from that module code (store-only)
    /// note that DeletePrefix can be a costly operation on large stores
    #[prost(uint64, tag="11")]
    pub total_store_deleteprefix_count: u64,
    /// store_size_bytes is the uncompressed size of the full KV store for that module, from the last 'merge' operation (store-only)
    #[prost(uint64, tag="12")]
    pub store_size_bytes: u64,
    /// total_store_merging_time_ms is the time spent merging partial stores into a full KV store for that module (store-only)
    #[prost(uint64, tag="13")]
    pub total_store_merging_time_ms: u64,
    /// store_currently_merging is true if there is a merging operation (partial store to full KV store) on the way.
    #[prost(bool, tag="14")]
    pub store_currently_merging: bool,
    /// highest_contiguous_block is the highest block in the highest merged full KV store of that module (store-only)
    #[prost(uint64, tag="15")]
    pub highest_contiguous_block: u64,
}
/// ExternalCallMetric tracks usage of a chain-specific external call type (e.g., Ethereum
/// RPC calls) made by a module during processing.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalCallMetric {
    /// The name identifying the type of external call (e.g., "eth_call").
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// The total number of external calls of this type made.
    #[prost(uint64, tag="2")]
    pub count: u64,
    /// The total wall-clock time in milliseconds spent waiting for external calls of this type.
    #[prost(uint64, tag="3")]
    pub time_ms: u64,
}
/// StoreDelta represents a single key-value mutation in a `store` module's state for a
/// given block. Used in debug store output and initial snapshot data.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreDelta {
    /// The type of operation applied to this key.
    #[prost(enumeration="store_delta::Operation", tag="1")]
    pub operation: i32,
    /// The ordinal within the block at which this mutation occurred. Ordinals are
    /// monotonically increasing within a block and allow ordering mutations within
    /// the same block.
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    /// The store key that was mutated.
    #[prost(string, tag="3")]
    pub key: ::prost::alloc::string::String,
    /// The previous value of the key before this mutation (empty for CREATE operations).
    #[prost(bytes="vec", tag="4")]
    pub old_value: ::prost::alloc::vec::Vec<u8>,
    /// The new value of the key after this mutation (empty for DELETE operations).
    #[prost(bytes="vec", tag="5")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `StoreDelta`.
pub mod store_delta {
    /// Operation describes the type of mutation applied to the store key.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Operation {
        Unset = 0,
        Create = 1,
        Update = 2,
        Delete = 3,
    }
    impl Operation {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Operation::Unset => "UNSET",
                Operation::Create => "CREATE",
                Operation::Update => "UPDATE",
                Operation::Delete => "DELETE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSET" => Some(Self::Unset),
                "CREATE" => Some(Self::Create),
                "UPDATE" => Some(Self::Update),
                "DELETE" => Some(Self::Delete),
                _ => None,
            }
        }
    }
}
/// BlockRange represents a contiguous range of blocks [start_block, end_block).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BlockRange {
    /// The first block number in the range (inclusive).
    #[prost(uint64, tag="2")]
    pub start_block: u64,
    /// The last block number in the range (exclusive).
    #[prost(uint64, tag="3")]
    pub end_block: u64,
}
// @@protoc_insertion_point(module)
