// @generated
// This file is @generated by prost-build.
// Generated from spec by infra/substreams/codegen — do not edit by hand.
// Output contract: the frozen PoolBlock shape from the Substreams extraction
// plan. Exact quantities ride decimal strings so no consumer ever coerces a
// uint64/int256 through a double.

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapEvent {
    /// 0x-prefixed lowercase hex; the transaction that emitted the log.
    #[prost(string, tag="1")]
    pub transaction_hash: ::prost::alloc::string::String,
    /// The log's index within its block (as the block model reports it).
    #[prost(uint32, tag="2")]
    pub log_index: u32,
    /// 0x-prefixed lowercase hex; the pool that emitted the event.
    #[prost(string, tag="3")]
    pub pool: ::prost::alloc::string::String,
    /// Exact signed decimal integer (int256), raw token units of token0.
    #[prost(string, tag="4")]
    pub amount0_raw: ::prost::alloc::string::String,
    /// Exact signed decimal integer (int256), raw token units of token1.
    #[prost(string, tag="5")]
    pub amount1_raw: ::prost::alloc::string::String,
    /// Exact decimal integer (uint160).
    #[prost(string, tag="6")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    /// 0x-prefixed lowercase hex; the address that initiated the swap call.
    /// Routers and contracts appear here — never call senders distinct people.
    #[prost(string, tag="7")]
    pub sender: ::prost::alloc::string::String,
    /// 0x-prefixed lowercase hex; the address that received the swap output.
    #[prost(string, tag="8")]
    pub recipient: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolBlocks {
    /// Output schema version of this package's normalized shape.
    #[prost(uint32, tag="1")]
    pub schema_version: u32,
    /// The chain this package was generated for (spec chainId, e.g. 1 mainnet).
    #[prost(uint64, tag="2")]
    pub chain_id: u64,
    /// Block number (uint64; JSON consumers read it as a decimal string).
    #[prost(uint64, tag="3")]
    pub block_number: u64,
    /// 0x-prefixed lowercase hex block hash.
    #[prost(string, tag="4")]
    pub block_hash: ::prost::alloc::string::String,
    /// Block timestamp in seconds since epoch (uint64; decimal string in JSON).
    #[prost(uint64, tag="5")]
    pub block_timestamp_seconds: u64,
    /// Decoded Swap events from this block; may be empty (the envelope still
    /// proves the block was observed complete).
    #[prost(message, repeated, tag="6")]
    pub events: ::prost::alloc::vec::Vec<SwapEvent>,
}
// @@protoc_insertion_point(module)
